name: Deploy React App to AWS EBS via Docker and S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: form-flow-frontend
  EB_APPLICATION_NAME: form-flow
  EB_ENVIRONMENT_NAME: form-flow-fe-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to AWS ECR
      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      # Step 5: Tag the Docker image with the ECR repository URI
      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Step 6: Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest

      # Step 7: Create a Dockerrun.aws.json file
      - name: Create Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "'$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest'",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": 80
              }
            ]
          }' > Dockerrun.aws.json

      # Step 8: Deploy to AWS Elastic Beanstalk
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          # Create a new application version
          aws elasticbeanstalk create-application-version \
            --application-name $EB_APPLICATION_NAME \
            --version-label $(git rev-parse --short HEAD) \
            --source-bundle S3Bucket=elasticbeanstalk-$AWS_REGION-$AWS_ACCOUNT_ID,S3Key=default-dockerrun.zip \
            --region $AWS_REGION

          # Update the environment to use the new version
          aws elasticbeanstalk update-environment \
            --application-name $EB_APPLICATION_NAME \
            --environment-name $EB_ENVIRONMENT_NAME \
            --version-label $(git rev-parse --short HEAD) \
            --region $AWS_REGION